export const fetchcategorysucces={type:"FETCH_CATEGORY_SUCCESS"}
export const fetcheventsuccess={type: "FETCH_EVENT_SUCCESS"}
export const fetchevendetailtsuccess={type: "FETCH_EVENT_DETAIL_SUCCESS"}
export const fetchticketsuccess={type:"FETCH_TICKET_SUCCESS"}
export const fetchticketcodesuccess={type:"FETCH_TICKET_CODE_SUCCESS"}
export const handlecategoryid={type:"HANDLE_CATEGORY_ID"}
export const handleeventid={type:"HANDLE_EVENT_ID"}
export const handleeventdetailid={type:"HANDLE_EVENT_DETAIL_ID"}
export const handleprice={type:"HANDLE_PRICE"}
export const handlequantity={type:"HANDLE_QUANTITY"}
export const clearstate={type:"CLEAR_STATE"}
export const fetchticketsavesuccess={type:"FETCH_TICKET_SAVE_SUCCESS"}
export const handleonsaleupdate={type:"HANDLE_ON_SALE_UPDATE"}
export const handlefreeupdate={type:"HANDLE_FREE_UPDATE"}
export const clearstateonstate={type:"CLEAR_STATE_ON_SALE"}
export const clearstatefree={type:"CLEAR_STATE_FREE"}
